import type { Metadata } from "next";
import { Inter, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "./NavBar";
import AuthProvider from "./auth/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

const SC = Source_Code_Pro({ 
	subsets: ["latin"],
	weight:['200', '400', '500']
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={SC.className}>
				<AuthProvider>
					<Navbar  />
					<main className="p-5">{children}</main>
				</AuthProvider>
			</body>
		</html>
	);
}
